#!/usr/bin/env python3
"""Compress the game's text catalog into a C header.

Runs as a PlatformIO pre-script (see platformio.ini), writing
$BUILD_DIR/gen/game_text.h from src/game_text.txt on every build. Can also
be run by hand to see what it produces:

    scripts/gen_text.py src/game_text.txt out.h

Compression is byte-pair encoding: the text is 7-bit ASCII, so byte values
0x80..0xFF are free to stand for a pair of other bytes (either of which may
itself be a pair). The most frequent adjacent pair across all messages is
replaced repeatedly until 128 codes are used or no pair repeats often enough
to pay for its 2-byte table entry. Messages are NUL-terminated and stored
back to back; the decoder in game.c walks to the n-th one.
"""

import os
import sys
from os.path import join

MAX_CODES = 128


def parse_catalog(path):
    msgs = []   # (name, text)
    name, lines = None, []

    def flush():
        if name is None:
            return
        while lines and not lines[-1].strip():
            lines.pop()
        msgs.append((name, "\n".join(lines) + "\n"))

    with open(path) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if line.startswith("#"):
                continue
            if line.startswith("@"):
                flush()
                name, lines = line[1:].strip(), []
                if not name.isidentifier():
                    sys.exit("%s:%d: bad message name %r" % (path, lineno, name))
                if any(n == name for n, _ in msgs):
                    sys.exit("%s:%d: duplicate message %s" % (path, lineno, name))
                continue
            if name is None:
                if line.strip():
                    sys.exit("%s:%d: text before the first @NAME" % (path, lineno))
                continue
            if any(ord(c) < 0x20 or ord(c) > 0x7E for c in line):
                sys.exit("%s:%d: only printable ASCII is allowed" % (path, lineno))
            lines.append(line.rstrip())
    flush()
    return msgs


def bpe(seqs):
    pairs = []
    for code in range(0x80, 0x80 + MAX_CODES):
        counts = {}
        for s in seqs:
            for i in range(len(s) - 1):
                p = (s[i], s[i + 1])
                counts[p] = counts.get(p, 0) + 1
        if not counts:
            break
        best, n = max(counts.items(), key=lambda kv: kv[1])
        # Each replacement saves a byte; the table entry costs two.
        if n < 3:
            break
        pairs.append(best)
        for idx, s in enumerate(seqs):
            out, i = [], 0
            while i < len(s):
                if i + 1 < len(s) and (s[i], s[i + 1]) == best:
                    out.append(code)
                    i += 2
                else:
                    out.append(s[i])
                    i += 1
            seqs[idx] = out
    return pairs, seqs


def expand(code, pairs):
    if code < 0x80:
        return [code]
    a, b = pairs[code - 0x80]
    return expand(a, pairs) + expand(b, pairs)


def c_bytes(data, indent="\t", per_line=16):
    rows = []
    for i in range(0, len(data), per_line):
        rows.append(indent + ", ".join("0x%02X" % b for b in data[i:i + per_line]) + ",")
    return "\n".join(rows)


def generate(src, dst):
    msgs = parse_catalog(src)
    raw = [list(text.encode("ascii")) for _, text in msgs]
    pairs, packed = bpe([list(r) for r in raw])

    # Round-trip check, so a generator bug fails the build, not the badge.
    for (name, _), r, p in zip(msgs, raw, packed):
        if sum((expand(c, pairs) for c in p), []) != r:
            sys.exit("gen_text: round trip failed for %s" % name)

    blob = []
    for p in packed:
        blob += p + [0]

    raw_size = sum(len(r) + 1 for r in raw)
    packed_size = len(blob) + 2 * len(pairs)

    out = []
    out.append("// Generated by scripts/gen_text.py from src/game_text.txt -- do not edit.")
    out.append("// %d messages: %d bytes of text packed into %d (%d pair codes)."
               % (len(msgs), raw_size, packed_size, len(pairs)))
    out.append("#ifndef _GAME_TEXT_H")
    out.append("#define _GAME_TEXT_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("enum text_id {")
    for name, _ in msgs:
        out.append("\tT_%s," % name)
    out.append("\tT_COUNT")
    out.append("};")
    out.append("")
    out.append("#ifdef GAME_TEXT_DATA")
    out.append("")
    out.append("#define TEXT_FIRST_PAIR 0x80")
    out.append("")
    out.append("static const uint8_t text_pairs[%d][2] = {" % max(len(pairs), 1))
    for i in range(0, max(len(pairs), 1), 8):
        row = pairs[i:i + 8] or [(0, 0)]
        out.append("\t" + " ".join("{ 0x%02X, 0x%02X }," % p for p in row))
    out.append("};")
    out.append("")
    out.append("static const uint8_t text_blob[%d] = {" % len(blob))
    out.append(c_bytes(blob))
    out.append("};")
    out.append("")
    out.append("#endif")
    out.append("")
    out.append("#endif")
    content = "\n".join(out) + "\n"

    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    try:
        with open(dst) as f:
            if f.read() == content:
                return raw_size, packed_size   # unchanged: keep the mtime, skip rebuilds
    except FileNotFoundError:
        pass
    with open(dst, "w") as f:
        f.write(content)
    return raw_size, packed_size


try:
    Import("env")  # noqa: F821 -- provided by SCons under PlatformIO
except NameError:
    env = None

if env is not None:
    gen_dir = join(env.subst("$BUILD_DIR"), "gen")
    raw_size, packed_size = generate(join(env.subst("$PROJECT_DIR"), "src", "game_text.txt"),
                                     join(gen_dir, "game_text.h"))
    print("Game text: %d bytes packed into %d" % (raw_size, packed_size))
    env.Append(CPPPATH=[gen_dir])
elif __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    raw_size, packed_size = generate(sys.argv[1], sys.argv[2])
    print("%d bytes packed into %d" % (raw_size, packed_size))
